language: java

before_install:
  - chmod +x gradlew


jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

sudo: false



script:
  - ./gradlew build


notifications:
  email:
    recipients:
      - witold.jnc@gmail.com
    on_success: always
    on_failure: always